--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.225.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2025.11.10 12:37:13
-- Server version: 10.4.32
--

SET NAMES 'utf8';

INSERT INTO mobilok_db.markak(marka_id, marka_nev, orszag, alapitas_ev) VALUES
(1, 'Samsung', 'Dél-Korea', 1938);
INSERT INTO mobilok_db.markak(marka_id, marka_nev, orszag, alapitas_ev) VALUES
(2, 'Apple', 'USA', 1976);
INSERT INTO mobilok_db.markak(marka_id, marka_nev, orszag, alapitas_ev) VALUES
(3, 'Xiaomi', 'Kína', 2010);
INSERT INTO mobilok_db.markak(marka_id, marka_nev, orszag, alapitas_ev) VALUES
(4, 'OnePlus', 'Kína', 2013);
INSERT INTO mobilok_db.markak(marka_id, marka_nev, orszag, alapitas_ev) VALUES
(5, 'Nokia', 'Finnország', 1865);