--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.225.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2025.11.10 12:37:13
-- Server version: 10.4.32
--

SET NAMES 'utf8';

INSERT INTO mobilok_db.telefonok(telefon_id, tipus_nev, megjelenes_ev, ar, marka_id) VALUES
(1, 'Galaxy A25', 2024, 120000, 1);
INSERT INTO mobilok_db.telefonok(telefon_id, tipus_nev, megjelenes_ev, ar, marka_id) VALUES
(2, 'iPhone 15', 2023, 450000, 2);
INSERT INTO mobilok_db.telefonok(telefon_id, tipus_nev, megjelenes_ev, ar, marka_id) VALUES
(3, 'Redmi Note 13', 2024, 110000, 3);
INSERT INTO mobilok_db.telefonok(telefon_id, tipus_nev, megjelenes_ev, ar, marka_id) VALUES
(4, 'OnePlus 12', 2024, 350000, 4);
INSERT INTO mobilok_db.telefonok(telefon_id, tipus_nev, megjelenes_ev, ar, marka_id) VALUES
(5, 'Nokia G42', 2023, 90000, 5);